image: node:14-buster

stages:
    - build
    - deploy

variables:
    CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    CONTAINER_NAME: $CI_PROJECT_NAME

build:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    script:
        - cp $NPMRC .npmrc
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t $CONTAINER_IMAGE .
        - docker push $CONTAINER_IMAGE

deploy:
    image: alpine:latest
    stage: deploy
    script:
        - chmod og= $ID_RSA
        - apk update && apk add openssh-client
        - ssh -i $ID_RSA -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
        - ssh -i $ID_RSA -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_IP "docker pull $CONTAINER_IMAGE"
        - ssh -i $ID_RSA -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_IP "docker container rm -f $CONTAINER_NAME || true"
        - scp -i $ID_RSA $ENV_FILE $DEPLOY_USER@$DEPLOY_IP:/tmp/.env
        - ssh -i $ID_RSA -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_IP "docker run -d -p $DEPLOY_PORT:80 --name $CONTAINER_NAME --env-file /tmp/.env $CONTAINER_IMAGE && rm /tmp/.env"
