stages:
  - version
  - publish

version:
  image: python:3.7-stretch
  stage: version
  script:
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts && chmod 644 ~/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - python3 -m scripts.update-git-tags
  only:
    - master
  except:
      - tags

publish:
  image: node:14
  stage: publish
  script:
    - npm config set @mmo.delivery:registry https://gitlab.com/api/v4/projects/29850527/packages/npm/
    - npm config set -- '//gitlab.com/api/v4/projects/29850527/packages/npm/:_authToken' "$CI_JOB_TOKEN"
    # catching error from publishing in case upcoming version is the same as previous
    - npm publish || true
  only:
    - master
  except:
      - tags